#!/bin/bash
# Browser Cache Fix for Dashboard

echo "🔧 Dashboard Error Fix - Browser Cache Issue"
echo ""
echo "Issue: Browser showing 'receptionlist' typo in network requests"
echo "Cause: Browser cached old API endpoint with typo"
echo ""
echo "✅ Fixes Applied:"
echo "1. Frontend rebuilt with clean Docker build"
echo "2. Environment variables verified (correct URL)"
echo "3. Frontend container restarted"
echo ""
echo "🌐 Frontend Status:"
ssh droplet "docker ps | grep dashboard_nextjs"
echo ""
echo "🔍 Environment Check:"
ssh droplet "docker exec dashboard_nextjs env | grep API_BASE_URL"
echo ""
echo "📋 User Action Required:"
echo "1. Open dashboard in browser: https://dashboard.lexmakesit.com/app"
echo "2. Press Ctrl+Shift+R (or Cmd+Shift+R on Mac) to hard refresh"
echo "3. Or: Open DevTools > Application > Clear Storage > Clear site data"
echo "4. Or: Open in incognito/private window"
echo ""
echo "This will clear the cached API endpoint and use the correct one."
